kind: Deployment
apiVersion: apps/v1
metadata:
  name: seerep-server
  labels:
    app: seerep-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seerep-server
  template:
    metadata:
      labels:
        app: seerep-server
    spec:
      containers:
        - name: seerep-server
          image: 'ghcr.io/DFKI-NI/seerep_server:latest'
          tty: true
          ports:
            - containerPort: 9090
              protocol: TCP
          args: ["-c", "/seerep/src/seerep.cfg"]
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /mnt/seerep-data
              name: seerep-data
            - mountPath: /seerep/src/seerep.cfg
              name: config
              subPath: seerep.cfg
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      volumes:
        - name: seerep-data
          persistentVolumeClaim:
            claimName: seerep-pv-claim
        - name: config
          configMap:
            name: seerep-cfg
  strategy:
    type: Recreate
